import numpy as np
import tifffile


def test_load_volume_from_bytes_reads_a_real_tiff(tmp_path):
    from mvp.pipeline import load_volume_from_bytes

    volume = (np.random.rand(4, 3, 32, 32) * 1000).astype(np.uint16)
    tiff_path = tmp_path / "in.tif"
    tifffile.imwrite(str(tiff_path), volume)

    loaded = load_volume_from_bytes("in.tif", tiff_path.read_bytes(), tmp_path / "raw")
    assert loaded.shape == volume.shape
    assert np.array_equal(loaded, volume)


def test_load_volume_from_bytes_adds_z_axis_for_3d_tiff(tmp_path):
    from mvp.pipeline import load_volume_from_bytes

    volume = (np.random.rand(4, 32, 32) * 1000).astype(np.uint16)  # no explicit Z axis
    tiff_path = tmp_path / "in.tif"
    tifffile.imwrite(str(tiff_path), volume)

    loaded = load_volume_from_bytes("in.tif", tiff_path.read_bytes(), tmp_path / "raw")
    assert loaded.shape == (4, 1, 32, 32)


def test_load_volume_from_bytes_rejects_unsupported_extension(tmp_path):
    from mvp.pipeline import load_volume_from_bytes

    try:
        load_volume_from_bytes("in.csv", b"not an image", tmp_path / "raw")
        assert False, "expected ValueError for an unsupported extension"
    except ValueError:
        pass


def test_run_detection_and_tracking_without_cnn_on_synthetic_data():
    """The actual point: prove the synthetic test file this repo ships
    (mvp/test_data/synthetic_test.tif, generated by mvp/make_test_data.py) produces at least
    one detected division when run through the real pipeline, --no-cnn mode. If someone
    regenerates that file with parameters that break this (see the amplitude/offset comments in
    make_test_data.py), this test is what catches it."""
    from pathlib import Path
    from mvp.pipeline import run_detection_and_tracking

    tiff_path = Path(__file__).resolve().parent.parent / "mvp" / "test_data" / "synthetic_test.tif"
    if not tiff_path.exists():
        from mvp.make_test_data import main as make_test_data_main
        make_test_data_main()

    volume = tifffile.imread(str(tiff_path))
    if volume.ndim == 3:
        volume = volume[:, None, :, :]

    result = run_detection_and_tracking(volume, use_cnn_filter=False)
    assert len(result.nodes) > 0
    assert result.n_divisions() >= 1
